# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/xiaobai/Workspace/labs/opengl-samples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/xiaobai/Workspace/labs/opengl-samples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xiaobai/Workspace/labs/opengl-samples/CMakeFiles /Users/xiaobai/Workspace/labs/opengl-samples/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xiaobai/Workspace/labs/opengl-samples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cg_opengl

# Build rule for target.
cg_opengl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cg_opengl
.PHONY : cg_opengl

# fast build rule for target.
cg_opengl/fast:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/build
.PHONY : cg_opengl/fast

gl_labs.o: gl_labs.cpp.o

.PHONY : gl_labs.o

# target to build an object file
gl_labs.cpp.o:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_labs.cpp.o
.PHONY : gl_labs.cpp.o

gl_labs.i: gl_labs.cpp.i

.PHONY : gl_labs.i

# target to preprocess a source file
gl_labs.cpp.i:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_labs.cpp.i
.PHONY : gl_labs.cpp.i

gl_labs.s: gl_labs.cpp.s

.PHONY : gl_labs.s

# target to generate assembly for a file
gl_labs.cpp.s:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_labs.cpp.s
.PHONY : gl_labs.cpp.s

gl_main.o: gl_main.cpp.o

.PHONY : gl_main.o

# target to build an object file
gl_main.cpp.o:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_main.cpp.o
.PHONY : gl_main.cpp.o

gl_main.i: gl_main.cpp.i

.PHONY : gl_main.i

# target to preprocess a source file
gl_main.cpp.i:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_main.cpp.i
.PHONY : gl_main.cpp.i

gl_main.s: gl_main.cpp.s

.PHONY : gl_main.s

# target to generate assembly for a file
gl_main.cpp.s:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_main.cpp.s
.PHONY : gl_main.cpp.s

gl_utils.o: gl_utils.cpp.o

.PHONY : gl_utils.o

# target to build an object file
gl_utils.cpp.o:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_utils.cpp.o
.PHONY : gl_utils.cpp.o

gl_utils.i: gl_utils.cpp.i

.PHONY : gl_utils.i

# target to preprocess a source file
gl_utils.cpp.i:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_utils.cpp.i
.PHONY : gl_utils.cpp.i

gl_utils.s: gl_utils.cpp.s

.PHONY : gl_utils.s

# target to generate assembly for a file
gl_utils.cpp.s:
	$(MAKE) -f CMakeFiles/cg_opengl.dir/build.make CMakeFiles/cg_opengl.dir/gl_utils.cpp.s
.PHONY : gl_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cg_opengl"
	@echo "... gl_labs.o"
	@echo "... gl_labs.i"
	@echo "... gl_labs.s"
	@echo "... gl_main.o"
	@echo "... gl_main.i"
	@echo "... gl_main.s"
	@echo "... gl_utils.o"
	@echo "... gl_utils.i"
	@echo "... gl_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

